# Generated by Django 3.1.3 on 2020-11-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('installation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionID',
            fields=[
                ('sessionID', models.UUIDField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
                ('cookie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eventProcessor.client')),
            ],
        ),
    ]
