# Generated by Django 3.1.3 on 2020-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventProcessor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='direction',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='sensor',
            name='postalCode',
            field=models.IntegerField(default=None),
        ),
    ]
